---
version: '3'
services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./web:/mosquitto/web
      - mosquitto-data:/mosquitto/data
volumes:
  mosquitto-data:
